language: java
jdk:
  - oraclejdk8

sudo: false

before_install:
  - openssl aes-256-cbc -K $encrypted_08f0b0a0f8f3_key -iv $encrypted_08f0b0a0f8f3_iv -in gnupg-keys/secring.gpg.enc -out secring.gpg -d
  - openssl aes-256-cbc -K $encrypted_08f0b0a0f8f3_key -iv $encrypted_08f0b0a0f8f3_iv -in gnupg-keys/pubring.gpg.enc -out pubring.gpg -d

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy -Dgpg.defaultKeyring=false -Dgpg-keyname=BF230DCD -Dgpg.passphrase=${env.OSSRH_PASS} -Dgpg.publicKeyring=pubring.gpg -Dgpg.secretKeyring=secring.gpg --settings ~/settings.xml
