language: java
jdk:
- oraclejdk8
sudo: false

before_install:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD
  -in gnupg-keys/pubring.gpg.enc -out pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD
  -in gnupg-keys/secring.gpg.enc -out secring.gpg -d

after_success:
- echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>"
  > ~/settings.xml
- mvn deploy -Dgpg.defaultKeyring=false -Dgpg-keyname=BF230DCD -Dgpg.passphrase=${env.OSSRH_PASS}
  -Dgpg.publicKeyring=pubring.gpg -Dgpg.secretKeyring=secring.gpg --settings
  ~/settings.xml

env:
  global:
    secure: LpJ0mAFRNPRea5CRZPYiDbcG8ah3PPDC6uG4671MkY5I+5sOXK87Nj/eyhxLWuJSW+HddYYkive9uGi+yGgTOgdEi4IrGtR0vphIPykwhcvG68VwUsXgxZFWNb6wMjxn9UwiP1HxvVFPoTr+qEj/pPpFYIVRMchdoGrLpdnnpZ8=
