language: java
jdk:
- oraclejdk8
sudo: false

after_success:

- echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>"
  > ~/settings.xml

- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD
  -in gnupg-keys/secring.gpg.enc -out ~/secring.gpg -d

- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD
  -in gnupg-keys/pubring.gpg.enc -out ~/pubring.gpg -d

- git config credential.helper "store --file=.git/credentials"

- echo "https://${Travis-atam4j}:@github.com" > .git/credentials

- cat .git/credentials

- mvn release:prepare release:perform -B

- mvn deploy -Prelease -Dgpg.defaultKeyring=false -Dgpg-keyname=BF230DCD -Dgpg.passphrase=$GPGKEY_PASSPHRASE
  -Dgpg.publicKeyring=~/pubring.gpg -Dgpg.secretKeyring=~/secring.gpg -DskipTests=true
  --settings ~/settings.xml

env:
  global:
  - secure: LpJ0mAFRNPRea5CRZPYiDbcG8ah3PPDC6uG4671MkY5I+5sOXK87Nj/eyhxLWuJSW+HddYYkive9uGi+yGgTOgdEi4IrGtR0vphIPykwhcvG68VwUsXgxZFWNb6wMjxn9UwiP1HxvVFPoTr+qEj/pPpFYIVRMchdoGrLpdnnpZ8=
  - secure: oQndLtmmoT7DmbxYb2OnlutlyICXQMYiSc9wZxkcg2M5d4mzLe2wPEaCcZEwykGLiXJpts6guuTvKa9frINj1ohM7H2w+eOqfUHsZFech3cYydtYYqbNtVhKTy0aQqgl1S0xtufc7a95US7XNaT9taghEozWhRa0WBNcdFnUDBs=
