initialDelayInMillis: 1
periodInMillis: 1

testClasses:
  - me.atam.atam4j.dummytests.PassingTestWithNoCategory

server:

  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
      - type: http
        port: 8081

  requestLog:
    appenders:
      - type: console
        timeZone: UTC

logging:
  level: ERROR
  loggers:
    io.dropwizard: DEBUG
  appenders:
    - type: console
      logFormat: '[%d{ISO8601}] %-5level [%thread] %logger{15} - %msg%n'
