# Dropwizard server configuration
server:

  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
      - type: http
        port: 8081

  requestLog:
    appenders:
      - type: console
        timeZone: UTC

logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG
  appenders:
    - type: console
