# Dropwizard server configuration
initialDelayInMillis: 1

testClasses:
  - me.atam.atam4j.dummytests.PassingTest
  - me.atam.atam4j.dummytests.FailingTest

server:

  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
      - type: http
        port: 8081

  requestLog:
    appenders:
      - type: console
        timeZone: UTC

logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG
  appenders:
    - type: console
