initialDelayInMillis: 1
periodInMillis: 60000

testClasses:
  - me.atam.atam4j.dummytests.PassingTestWithNoCategory
  - me.atam.atam4j.dummytests.PassingTestsWithCategories

server:

  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
      - type: http
        port: 8081

  requestLog:
    appenders:
      - type: console
        timeZone: UTC

logging:
  level: ERROR
  loggers:
    io.dropwizard: INFO
    me.atam.atam4j: ERROR
  appenders:
    - type: console
      logFormat: '[%d{ISO8601}] %-5level [%thread] %logger{15} - %msg%n'
